"""Forecast policies — determine how historical observations map to future bins."""

from __future__ import annotations

import math
from abc import ABC, abstractmethod
from datetime import date

import pandas as pd
from autoslo.tuner.reservoir import QueryReservoir

from autoslo.workload_definition.workload import Workload

import numpy as np
from pathlib import Path

from typing import Optional

from autoslo.utils.class_with_factory import ClassWithFactory


class ForecastPolicy(ClassWithFactory):
    """Abstract base class for forecast policies."""

    def __init__(
        self,
        reservoir: QueryReservoir,
        *args,
        **kwargs,
    ) -> None:
        """
        Initialize the forecast policy.

        Parameters
        ----------
        reservoir :
            Historical query reservoir to draw observations from.
        """

        self.reservoir = reservoir
        self.schema_name = self.reservoir.schema_name

    def forecast(
        self,
        target_date: date,
        seed: int = 42,
        workload_name: str = "forecast",
    ) -> Workload:
        """Return a forcasted workload for the target interval.

        Parameters
        ----------.
        target_date :
            Date of the target interval to forecast for.
        seed :
            Random seed for reproducibility.
        workload_name :
            Name for the forecasted workload.
        """

        rows = []
        query_idx = 0

        for i in range(24):
            bin_df = self._build_bin_df(target_date, i)
            if bin_df.empty:
                continue

            n_samples = self._n_samples(target_date, i, bin_df)
            if n_samples == 0:
                continue

            # Sample with replacement from the 'query_text_id' column, based on
            # the relative weights of the "count" column.
            sampled_ids = bin_df.sample(
                n=n_samples,
                weights="count",
                replace=True,
                random_state=seed,
            )["query_text_id"]

            # Given the number of arrivals, the arrival times for a Poisson
            # process are uniformly distributed within the hour.
            sampled_relative_start_times = sorted(
                np.random.default_rng(seed).uniform(0, 3600, size=n_samples)
            )
            base_start_time = pd.Timestamp(target_date) + pd.Timedelta(hours=i)

            for query_text_id, rel_start_time in zip(
                sampled_ids, sampled_relative_start_times
            ):
                if rel_start_time > 3600:
                    break
                rows.append(
                    {
                        "query_id": f"forecast_{query_idx:06d}",
                        "abs_start_time": (
                            base_start_time
                            + pd.Timedelta(seconds=rel_start_time)
                        ),
                        "query_text_id": query_text_id,
                        "repetition_id": 0,
                    }
                )

                query_idx += 1

        forecast_df = pd.DataFrame(
            rows, columns=Workload.WORKLOAD_SCHEMA_COLUMNS
        )
        workload = Workload(workload_name, self.schema_name, forecast_df)
        return workload

    def forecast_n_scenarios(
        self,
        target_date: date,
        n_scenarios: int,
        initial_seed: int = 42,
        workload_name_prefix: str = "f",
        out_dir: Optional[Path] = None,
    ) -> tuple[list[Workload], list[Path]]:
        """
        Return a list of forecasted workloads for the target day. Optionally
        also persist them.

        Parameters
        ----------.
        target_date :
           Date of the target day to forecast for.
        n_scenarios :
            Number of independent forecasted workloads to generate for the
            target day.  Each workload is generated by calling `forecast`
            with a different seed to ensure different random samples across
            scenarios.
        initial_seed :
            Initial random seed for reproducibility.  The method will derive
            separate seeds **sequentially** for each scenario to ensure
            different random samples across scenarios.
        workload_name_prefix :
            Prefix for the forecasted workload names. The full name for each
            workload will be `{workload_name_prefix}_{i}`, where `i` is the
            scenario index (starting from 0).
        out_dir :
            If provided, the directory to persist the forecasted workloads to.

        Returns
        -------
        workloads :
            The list of forecasted workloads.
        paths :
            If *out_dir* is provided, the list of paths to which the forecasted
            workloads were persisted. Otherwise, an empty list.
        """

        workloads: list[Workload] = []
        for i in range(n_scenarios):
            workload_name = f"{workload_name_prefix}_{i}"
            workload_seed = initial_seed + i
            workload = self.forecast(
                target_date, seed=workload_seed, workload_name=workload_name
            )
            workloads.append(workload)

        if out_dir is None:
            return workloads, []

        out_dir.mkdir(parents=True, exist_ok=True)
        paths = []
        for i, workload in enumerate(workloads):
            path = workload.save(out_dir=out_dir, overwrite=True)
            paths.append(path)
        return workloads, paths

    @abstractmethod
    def _build_bin_df(self, target_date: date, hour: int) -> pd.DataFrame:
        """Return the DataFrame of historical observations for the specified bin."""
        raise NotImplementedError

    @abstractmethod
    def _n_samples(
        self, target_date: date, hour: int, bin_df: pd.DataFrame
    ) -> int:
        """Return the number of samples to draw for the specified bin."""
        raise NotImplementedError


class OneDayForecastPolicy(ForecastPolicy):
    """
    Base the forecast on yesterday only.
    Useful as a simple baseline.
    """

    @property
    def name(self) -> str:
        return self.__class__.__name__

    def _build_bin_df(self, target_date: date, hour: int) -> pd.DataFrame:
        yesterday = target_date - pd.Timedelta(days=1)
        return self.reservoir.bin_df(yesterday, hour)

    def _n_samples(
        self, target_date: date, hour: int, bin_df: pd.DataFrame
    ) -> int:
        return int(bin_df["count"].sum())


class SevenDaysFlatForecastPolicy(ForecastPolicy):
    """
    Base the forecast for each hour on the average of the past 7 days for that
    hour, with equal weighting.
    """

    @property
    def name(self):
        return self.__class__.__name__

    def _build_bin_df(self, target_date: date, hour: int) -> pd.DataFrame:
        week_start = target_date - pd.Timedelta(days=7)
        superbin_list = [
            self.reservoir.bin_df(week_start + pd.Timedelta(days=d), hour)
            for d in range(7)
        ]
        return pd.concat(superbin_list)

    def _n_samples(
        self, target_date: date, hour: int, bin_df: pd.DataFrame
    ) -> int:
        num_active_days = bin_df["date"].nunique()
        if num_active_days == 0:
            return 0
        return int(round(bin_df["count"].sum() / num_active_days))


class SameDayOnceForecastPolicy(ForecastPolicy):
    """
    Base the forecast on the same day of the previous week.
    If there are no observations for that day, there are two cases:
        1) The cluster was not yet instantiated; in this case, try one day ago.
        2) The cluster was instantiated but there were simply no queries; in
              this case, forecast zero queries.
    Useful as a simple baseline.
    """

    @property
    def name(self) -> str:
        return self.__class__.__name__

    def _build_bin_df(self, target_date: date, hour: int) -> pd.DataFrame:
        one_week_ago = target_date - pd.Timedelta(days=7)
        one_week_ago_bin_df = self.reservoir.bin_df(one_week_ago, hour)
        if not one_week_ago_bin_df.empty or (
            one_week_ago >= self.reservoir.min_date
        ):
            return one_week_ago_bin_df

        one_day_ago = target_date - pd.Timedelta(days=1)
        one_day_ago_bin_df = self.reservoir.bin_df(one_day_ago, hour)
        return one_day_ago_bin_df

    def _n_samples(
        self, target_date: date, hour: int, bin_df: pd.DataFrame
    ) -> int:
        return int(bin_df["count"].sum())


class SameDayExponentialForecastPolicy(ForecastPolicy):
    """
    Base the forecast on past instances of the same day, with exponentially
    decaying weights. If there are no observations for that day, there are two cases:
        1) The cluster was not yet instantiated; in this case, try one day ago.
        2) The cluster was instantiated but there were simply no queries; in
              this case, forecast zero queries.
    """

    def __init__(
        self,
        reservoir: QueryReservoir,
        decay_factor: float = 0.5,
        *args,
        **kwargs,
    ) -> None:
        super().__init__(reservoir, *args, **kwargs)
        self.decay_factor = decay_factor

    def _build_bin_df(self, target_date: date, hour: int) -> pd.DataFrame:
        weight = 1.0
        day = target_date - pd.Timedelta(days=7)
        superbin_list = []
        while day >= self.reservoir.min_date:
            bin_df = self.reservoir.bin_df(day, hour)
            if not bin_df.empty:
                bin_df = bin_df.copy()
                bin_df["count"] *= weight  # apply the weight to the count
            weight *= (
                self.decay_factor
            )  # decay by the specified factor every week
            day -= pd.Timedelta(days=7)
            superbin_list.append(bin_df)

        if len(superbin_list) > 0:
            return pd.concat(superbin_list)

        if (target_date - pd.Timedelta(days=7)) >= self.reservoir.min_date:
            # Should return an empty DataFrame with the correct columns if there
            # are no observations but the date is within the reservoir's range.
            return pd.DataFrame(columns=self.reservoir.BIN_DF_COLUMNS)

        # If we get here, it means there are no observations and the date is
        # before the reservoir's range, so we should try one day ago instead.
        one_day_ago = target_date - pd.Timedelta(days=1)
        one_day_ago_bin_df = self.reservoir.bin_df(one_day_ago, hour)

        return one_day_ago_bin_df

    @property
    def name(self) -> str:
        return f"{self.__class__.__name__}(decay_factor={self.decay_factor})"

    def _n_samples(
        self, target_date: date, hour: int, bin_df: pd.DataFrame
    ) -> int:

        # Are we in the fallback case where we had to look at one day ago
        # instead of one week ago?
        if bin_df["date"].nunique() == 1 and (
            bin_df["date"].iloc[0] == (target_date - pd.Timedelta(days=1))
        ):
            return int(bin_df["count"].sum())

        # Take a weighted average of the past counts, where the weights are the
        # same as those applied in _build_bin_df.
        total_weight = 0.0
        weighted_count_sum = 0.0
        weight = 1.0
        day = target_date - pd.Timedelta(days=7)
        while day >= self.reservoir.min_date:
            day_bin_df = self.reservoir.bin_df(day, hour)
            day_count = day_bin_df["count"].sum()
            weighted_count_sum += weight * day_count
            total_weight += weight
            weight *= (
                self.decay_factor
            )  # decay by the specified factor every week
            day -= pd.Timedelta(days=7)
        if total_weight == 0:
            return 0

        return int(round(weighted_count_sum / total_weight))
