# Anything that is a list is grid searched over during training.

model_params:
  random_seed: 42
  model_type: xgboost
  num_boost_rounds: [100, 200]
  max_depth: [15, 30]
  monotonic_rpu: [true, false]
  objective_params:
    - objective_type: built-in
      objective: reg:quantileerror
      quantile_alpha: 0.95
    - objective_type: built-in
      objective: reg:quantileerror
      quantile_alpha: 0.99
    # - objective_type: built-in
    #   objective: reg:squarederror
    # - objective_type: built-in
    #   objective: reg:absoluteerror
    - objective_type: custom
      objective: asymmetric_mse
      heavy_side: 10
      light_side: 0.5
    - objective_type: custom
      objective: asymmetric_thresholded_mse
      heavy_side: 3
      light_side: 1
      low_threshold: 10.0
      low_value_weight: 0.2
    - objective_type: custom
      objective: asymmetric_thresholded_mse
      heavy_side: 2
      light_side: 1
      low_threshold: 10.0
      low_value_weight: 0.2
    - objective_type: custom
      objective: asymmetric_thresholded_mse
      heavy_side: 3
      light_side: 1
      low_threshold: 10.0
      low_value_weight: 0.1
data_params:
  dataset: redset
  bin_granularity: ["daily", "hourly"]
  train_split_name: train
  validation_split_name: validation
  test_split_name: test
featurization_params:
  - featurizer_name: FMinimal
    label_in_log_space: true
    features_summary_metric: ["p95", "p99", "mean"]
    label_summary_metric: ["p95", "p99"]
    interarrival_summary_metric: ["p1", "p5"]
    use_num_queries: [true, false]
    use_interarrival_time: true
  - featurizer_name: FMinimal
    label_in_log_space: true
    features_summary_metric: ["p95", "p99", "mean"]
    label_summary_metric: ["p95", "p99"]
    interarrival_summary_metric: "p1"
    use_num_queries: true
    use_interarrival_time: false
  - featurizer_name: FExtended
    label_in_log_space: true
    label_summary_metric: ["p95", "p99"]
    use_num_queries: [true, false]
    use_interarrival_time: true 
  - featurizer_name: FExtended
    label_in_log_space: true
    label_summary_metric: ["p95", "p99"]
    use_num_queries: true
    use_interarrival_time: false 
